[build-system]
requires = ["setuptools>=65.5.1"]
build-backend = "setuptools.build_meta"

[project]
name = "auth0-python"
dynamic = ["version"]
description = "Auth0 Python SDK"
readme = "README.md"
authors = [
    {name = "Auth0", email = "support@auth0.com"}
]
license = {file = "LICENSE"}
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
requires-python = ">=3.7"
dependencies = [
    "requests>=2.14.0",
    "pyjwt[crypto]>=2.6.0",
]
[project.optional-dependencies]
test = ["coverage", "pre-commit"]
async = ["aiohttp"]
[project.urls]
homepage = "https://github.com/auth0/auth0-python"
documentation = "https://www.auth0.com/docs"
changelog = "https://github.com/auth0/auth0-python/blob/master/CHANGELOG.md"

[tool.setuptools.dynamic]
version = {attr = "auth0.__version__"}
