version: 2.1

orbs:
  python: circleci/python@2.0.3
  ship: auth0/ship@0.5.0
  codecov: codecov/codecov@3

executors:
  python_3_10:
    docker:
      - image: cimg/python:3.10

jobs:
  build:
    executor: python_3_10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: pre-commit run --all-files
      - run: coverage run -m unittest
      - run: bash <(curl -s https://codecov.io/bash)
      - run: make -C docs html

workflows:
  main:
    jobs:
      - build
      - ship/python-publish:
          prefix-tag: false
          context:
            - publish-pypi
            - publish-gh
          filters:
            branches:
              only:
                - master
          requires:
            - build
